import { Activity } from "@/types";

export const MOCK_ACTIVITIES: Activity[] = [
    {
        id: "1",
        title: "Colosseum, Roman Forum & Palatine Hill Priority Access",
        location: "Rome, Italy",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCIrYgUY-fL88EexfBUukYoEscAoH9BnoFAhxe3dYuaD1oXUFSwMA-qtonVaaph38VtFX0vc3kL-9fdjG6C1vpyearFZWGObvPA11cJ0fKF1sassvtOHZ3pLdnjrVgBtI6ZlN9ll6B-45wXl1nt330OJXjwHZ06H7TomXp30lOtnbdCoB7QULkcs-dA1L6FrRPCIaKGFJp36ISnvh6iLBj55O129jDWdXxytyLz6UuG-NiQol8q-zcqS9libTwB9dwH5jKfyPXH4GR5",
        price: 55,
        currency: "€",
        rating: 4.5,
        reviewCount: 3204,
        duration: "3 hours",
        badge: "bestseller",
    },
    {
        id: "2",
        title: "Louvre Museum Timed-Entrance Ticket",
        location: "Paris, France",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBrtnm7-DMa2PT8F8CRvd_8LX-vGGsnCTwu6jTIFEckGgUeaZJkFhF_ztgqKDifr2Jw2PwU4taH2bV5g66F3Ip4qALkRqBRPrGyNftf5dtm7dKwW3Qk_i1lq0LS8bokuheh2bgBuxuc4k9nPFDKiK8VdzjxJW2N1Bzn7OG7030gxNvC2vxLpkR6OaIdsbwmkpRQoIeq6YrsRCnbg59v8lSOVFr6rf6XoWHpDA3ncS042DjW_sEFfb4C-w-34HOc-H2cHjWkyotKXcTA",
        price: 17,
        currency: "€",
        rating: 5,
        reviewCount: 12450,
        duration: "Valid 1 day",
        badge: "likely-to-sell-out",
    },
    {
        id: "3",
        title: "Great Barrier Reef Snorkeling & Diving Cruise",
        location: "Cairns, Australia",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDjrh4KBJEBKf9klt3hQWbEYdAGL-DnKofGS4Vnb-NJjr_BGu3CfoOaSZBsu_B2jT43XZomRwzX6Z5uLW4nNo6ZzXV1_kIhfaNBKdC8f9sw8RvVrudRHKd-5qZA4dt7-5_FZawXFkgZgRm3eJNiUGMUPbwx5ztREjuM61mzp4x9tuUVzC6VWXqFWM9yLC6Jsobw0H1IJYhzCy-J5OnEWKweBdEq_7Ze3hspxxZWix6GLJodkSy60OuzZXqjf3IGMxJInM-dm7qpCFbh",
        price: 140,
        currency: "€",
        rating: 4,
        reviewCount: 890,
        duration: "8 hours",
    },
    {
        id: "4",
        title: "Dubai: Burj Khalifa Level 124 & 125 Entry Ticket",
        location: "Dubai, UAE",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDNfzJXVoFe9sOJSrghYNPD8ayZf79nvElA6P3n2Lb8O6W6VGjdzO4H86-lvrrpgLNKxuhKpF2rcPc0YRvgM7HBqKJaESP1KJGm_1fzPADVPF-UjN9pcHV_5VWidJ1q1GI-zxkZoOIvIP8BcAGwUU1gmxb2L-xhQhsTVQjFZFZUkNvQ-IqPeTrJCLZ-uiDXXckor3XIKqVP8GrEuyPQ6-E5REjg7qRX_CvpgW9hi_qGWT_Oc-RpntocOyWkzIgVrG9dt4dZTD_1B3PH",
        price: 45,
        currency: "€",
        rating: 5,
        reviewCount: 15700,
        duration: "1.5 hours",
        badge: "top-pick",
    },
    // German Cities
    {
        id: "5",
        title: "Leipzig: Historische Stadtführung durch das Zentrum",
        location: "Leipzig, Germany",
        image: "https://images.unsplash.com/photo-1567359781514-3b964ea48311?w=800",
        price: 19,
        currency: "€",
        rating: 4.8,
        reviewCount: 342,
        duration: "2 hours",
        badge: "bestseller",
    },
    {
        id: "6",
        title: "Leipzig: Völkerschlachtdenkmal & Museum Tour",
        location: "Leipzig, Germany",
        image: "https://images.unsplash.com/photo-1599669454699-248893623440?w=800",
        price: 25,
        currency: "€",
        rating: 4.7,
        reviewCount: 189,
        duration: "2.5 hours",
    },
    {
        id: "7",
        title: "Leipzig: Bach-Museum & Thomaskirche Erlebnis",
        location: "Leipzig, Germany",
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800",
        price: 22,
        currency: "€",
        rating: 4.9,
        reviewCount: 256,
        duration: "3 hours",
        badge: "likely-to-sell-out",
    },
    {
        id: "8",
        title: "Berlin: Reichstag, Brandenburger Tor & Bundestag",
        location: "Berlin, Germany",
        image: "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800",
        price: 29,
        currency: "€",
        rating: 4.9,
        reviewCount: 4521,
        duration: "3 hours",
        badge: "bestseller",
    },
    {
        id: "9",
        title: "Berlin: Berliner Mauer & East Side Gallery Tour",
        location: "Berlin, Germany",
        image: "https://images.unsplash.com/photo-1528728329032-2972f65dfb3f?w=800",
        price: 24,
        currency: "€",
        rating: 4.8,
        reviewCount: 2876,
        duration: "2.5 hours",
    },
    {
        id: "10",
        title: "München: Marienplatz, Viktualienmarkt & Altstadt",
        location: "Munich, Germany",
        image: "https://images.unsplash.com/photo-1595867818082-083862f3d630?w=800",
        price: 27,
        currency: "€",
        rating: 4.7,
        reviewCount: 1834,
        duration: "2.5 hours",
        badge: "top-pick",
    },
    {
        id: "11",
        title: "München: Schloss Neuschwanstein Tagesausflug",
        location: "Munich, Germany",
        image: "https://images.unsplash.com/photo-1534313314376-a72289b6181e?w=800",
        price: 65,
        currency: "€",
        rating: 4.9,
        reviewCount: 3421,
        duration: "10 hours",
        badge: "bestseller",
    },
    {
        id: "12",
        title: "Hamburg: Hafen & Speicherstadt Bootstour",
        location: "Hamburg, Germany",
        image: "https://images.unsplash.com/photo-1566397220071-51c08d2389d2?w=800",
        price: 22,
        currency: "€",
        rating: 4.6,
        reviewCount: 1245,
        duration: "1.5 hours",
    },
];
