import { NextRequest, NextResponse } from "next/server";
import { getViatorProductDetails } from "@/lib/api/viator-client";

export async function GET(
    request: NextRequest,
    { params }: { params: Promise<{ id: string }> }
) {
    const { id } = await params;

    const productDetails = await getViatorProductDetails(id);

    // Mock fallback if API returns error (e.g. 401/404 because of invalid keys)
    if (productDetails.error && (id.startsWith("mock-") || productDetails.error.includes("401") || productDetails.error.includes("403"))) {
        return NextResponse.json({
            id: id,
            title: `Mock Activity Details for ${id}`,
            location: "Mock City, Country",
            image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80",
            price: 55.00,
            currency: "EUR",
            rating: 4.8,
            reviewCount: 320,
            duration: "3 hours",
            productCode: id,
            description: "This is a mock description because the API key is invalid or the product ID was generated by the mock search.",
            badge: "Bestseller",
            lat: 48.8566,
            lng: 2.3522
        });
    }

    if (productDetails.error) {
        // If 404 but not a mock product, return 404
        if (!id.startsWith("mock-")) {
            return NextResponse.json(
                { error: productDetails.error },
                { status: 404 }
            );
        }
        // Mock fallback for mock-* IDs
        return NextResponse.json({
            id: id,
            title: `Mock Activity Details for ${id}`,
            location: "Mock City, Country",
            image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80",
            images: [],
            price: 55.00,
            currency: "EUR",
            rating: 4.8,
            reviewCount: 320,
            duration: "3 hours",
            productCode: id,
            productUrl: "",
            description: "This is a mock description.",
            badge: "Bestseller",
            lat: 48.8566,
            lng: 2.3522
        });
    }

    // Extract best image
    const primaryImage = productDetails.images?.[0]?.variants?.find((v: any) => v.width >= 720)?.url
        || productDetails.images?.[0]?.variants?.[0]?.url
        || "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80";

    // Extract multiple images for gallery
    const allImages = productDetails.images?.slice(0, 5).map((img: any) => {
        const variant = img.variants?.find((v: any) => v.width >= 720) || img.variants?.[0];
        return variant?.url;
    }).filter(Boolean) || [];

    // Extract Location Coordinates (try itinerary first, then logistics)
    let lat, lng;
    // 1. Try Itinerary Point of Interest
    const firstPoi = productDetails.itinerary?.features?.[0]?.poi;
    if (firstPoi?.location?.ref) {
        // Can't easily get lat/lng from ref without another call, but maybe it's enriched?
        // Actually Viator API structure for POI sometimes has center
    }

    // 2. Try Logistics Start Location (Meeting Point)
    const startLocation = productDetails.logistics?.start?.[0]?.location;
    if (startLocation) {
        // Need to check specific structure where coords might be hidden
        // Often implicit in ref, but sometimes explicit
    }

    // Fallback if we can't find clear coords in detail: 0,0 or undefined
    // For now we rely on the component to geocode the string location if lat/lng missing

    // Transform Viator product to our format with safe fallbacks
    const activity = {
        id: productDetails.productCode,
        title: productDetails.title || "Untitled Activity",
        location: productDetails.destinations?.[0]?.name
            || productDetails.logistics?.start?.[0]?.location?.ref
            || "Location available at booking",
        image: primaryImage,
        images: allImages,
        price: productDetails.pricing?.summary?.fromPrice || 0,
        currency: productDetails.pricing?.currency || "EUR",
        rating: productDetails.reviews?.combinedAverageRating || 0,
        reviewCount: productDetails.reviews?.totalReviews || 0,
        duration: formatDuration(productDetails.duration),
        productCode: productDetails.productCode,
        productUrl: productDetails.productUrl || "",
        description: productDetails.description || "Description not available.",
        badge: productDetails.flags?.includes("BEST_SELLER") ? "Bestseller" : undefined,
        // Pass trough raw data for component to use if needed
        lat: undefined,
        lng: undefined
    };

    return NextResponse.json(activity);
}

function formatDuration(duration?: {
    fixedDurationInMinutes?: number;
    variableDurationFromMinutes?: number;
    variableDurationToMinutes?: number;
}): string {
    if (!duration) return "";

    if (duration.fixedDurationInMinutes) {
        const hours = Math.floor(duration.fixedDurationInMinutes / 60);
        const mins = duration.fixedDurationInMinutes % 60;
        if (hours > 0 && mins > 0) return `${hours}h ${mins}min`;
        if (hours > 0) return `${hours} hours`;
        return `${mins} min`;
    }

    if (duration.variableDurationFromMinutes && duration.variableDurationToMinutes) {
        const fromHours = Math.floor(duration.variableDurationFromMinutes / 60);
        const toHours = Math.floor(duration.variableDurationToMinutes / 60);
        return `${fromHours}-${toHours} hours`;
    }

    return "";
}
